// Command go-rest-api is the V1 template plugin: it generates a minimal,
// working Go REST API backend service. See docs/templates/authoring.md
// and ADR-0004 for the quality bar this must meet (the generated project
// must actually `go build` and `go test`, standalone, offline).
package main

import (
	"fmt"
	"os"
	"path/filepath"

	sdk "github.com/intruder0007/Cli/sdk/go/sdk"
)

type goRestAPITemplate struct{}

func (goRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"go.mod":                       goModFile(req.ProjectName),
		"main.go":                      mainGoFile(req.ProjectName),
		"internal/http/router.go":      routerGoFile(),
		"internal/http/router_test.go": routerTestGoFile(),
		"Makefile":                     makefileFile(),
		"README.md":                    readmeFile(req.ProjectName),
		".gitignore":                   gitignoreFile(),
	}

	var written []string
	for rel, content := range files {
		full := filepath.Join(req.TargetDir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return sdk.GenerateResponse{}, fmt.Errorf("creating directory for %s: %w", rel, err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			return sdk.GenerateResponse{}, fmt.Errorf("writing %s: %w", rel, err)
		}
		written = append(written, rel)
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"go build ./...",
			"go test ./...",
			"go run . # serves on :8080, GET /healthz",
		},
	}, nil
}

func goModFile(projectName string) string {
	return fmt.Sprintf("module %s\n\ngo 1.22\n", projectName)
}

func mainGoFile(projectName string) string {
	return fmt.Sprintf(`package main

import (
	"log"
	"net/http"

	httpinternal "%s/internal/http"
)

func main() {
	mux := httpinternal.NewRouter()
	log.Println("listening on :8080")
	if err := http.ListenAndServe(":8080", mux); err != nil {
		log.Fatal(err)
	}
}
`, projectName)
}

func routerGoFile() string {
	return `// Package httpinternal wires up the service's HTTP routes.
package httpinternal

import "net/http"

// NewRouter returns the service's HTTP handler.
func NewRouter() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", handleHealthz)
	return mux
}

func handleHealthz(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(` + "`{\"status\":\"ok\"}`" + `))
}
`
}

func routerTestGoFile() string {
	return `package httpinternal

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestHealthz(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	rec := httptest.NewRecorder()

	NewRouter().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("GET /healthz: got status %d, want %d", rec.Code, http.StatusOK)
	}
	if got := rec.Body.String(); got != ` + "`{\"status\":\"ok\"}`" + ` {
		t.Fatalf("GET /healthz: got body %q", got)
	}
}
`
}

func makefileFile() string {
	return `.PHONY: build test run

build:
	go build ./...

test:
	go test ./...

run:
	go run .
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Go REST API backend service, generated by Cli.

## Run

`+"```sh\nmake run\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\":\"ok\"}`"+`.

## Test

`+"```sh\nmake test\n```"+`
`, projectName)
}

func gitignoreFile() string {
	return "/bin/\n*.exe\n*.test\n"
}

func main() {
	sdk.Serve(goRestAPITemplate{})
}
