// Command java-rest-api generates a minimal, working Java HTTP API
// service. The plugin itself is Go (there's no Java SDK yet — see
// docs/architecture/roadmap.md), but what it generates is Java
// source. Same quality bar as go-rest-api/node-rest-api (ADR-0004):
// the generated project must actually run its own test suite,
// standalone, offline.
//
// Uses only com.sun.net.httpserver (the JDK's built-in HTTP server,
// available since Java 6) and java.net.http.HttpClient (built-in
// since Java 11) — no Maven, no dependencies to fetch. Builds and
// tests via plain javac/java, not a build tool, so nothing needs a
// Maven Central round-trip.
//
// NOT LOCALLY BUILDABLE/TESTABLE IN THIS ENVIRONMENT: no JDK was
// available where this template was written. Written carefully
// against standard com.sun.net.httpserver/java.net.http idioms and
// cross-checked against the JDK documentation, but the first real
// verification of the generated project is this repository's CI run
// (TestEndToEndGenerateJavaRestAPI), not a local one. Treat an initial
// red CI run as expected, not a process failure.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type javaRestAPITemplate struct{}

func (javaRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"src/Server.java":     serverJavaFile(),
		"src/ServerTest.java": serverTestJavaFile(),
		"README.md":           readmeFile(req.ProjectName),
		".gitignore":          gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"javac -d out src/*.java",
			"java -cp out ServerTest # runs the tests",
			"java -cp out Server # serves on :8080, GET /healthz",
		},
	}, nil
}

func serverJavaFile() string {
	return `import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;

public class Server {
    public static HttpServer createApp(int port) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/healthz", Server::handleHealthz);
        return server;
    }

    private static void handleHealthz(HttpExchange exchange) throws IOException {
        if (!"GET".equals(exchange.getRequestMethod())) {
            exchange.sendResponseHeaders(404, -1);
            exchange.close();
            return;
        }
        byte[] body = "{\"status\":\"ok\"}".getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().add("Content-Type", "application/json");
        exchange.sendResponseHeaders(200, body.length);
        try (OutputStream os = exchange.getResponseBody()) {
            os.write(body);
        }
    }

    public static void main(String[] args) throws IOException {
        HttpServer server = createApp(8080);
        server.start();
        System.out.println("listening on :8080");
    }
}
`
}

func serverTestJavaFile() string {
	return `import com.sun.net.httpserver.HttpServer;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class ServerTest {
    public static void main(String[] args) throws Exception {
        HttpServer server = Server.createApp(0);
        server.start();
        try {
            int port = server.getAddress().getPort();
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("http://127.0.0.1:" + port + "/healthz"))
                    .GET()
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            check(response.statusCode() == 200, "expected status 200, got " + response.statusCode());
            check(response.body().equals("{\"status\":\"ok\"}"), "expected body {\"status\":\"ok\"}, got " + response.body());
        } finally {
            server.stop(0);
        }

        System.out.println("all tests passed");
    }

    private static void check(boolean condition, String message) {
        if (!condition) {
            throw new AssertionError(message);
        }
    }
}
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Java HTTP API service, generated by Lumo.

## Run

`+"```sh\njavac -d out src/*.java\njava -cp out Server\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\":\"ok\"}`"+`.

## Test

`+"```sh\njavac -d out src/*.java\njava -cp out ServerTest\n```"+`

Uses only `+"`com.sun.net.httpserver`"+` (built into the JDK since Java 6)
and `+"`java.net.http.HttpClient`"+` (built in since Java 11) — no Maven, no
JUnit, no dependencies to fetch. `+"`ServerTest`"+` is a plain class with a
`+"`main`"+` method, not a test framework, so it never needs a Maven
Central round-trip either.
`, projectName)
}

func gitignoreFile() string {
	return "/out/\n*.class\n"
}

func main() {
	sdk.Serve(javaRestAPITemplate{})
}
