# Created for github.com/intruder0007/Lumo. See docs/architecture/distribution-protocol.md.
PackageIdentifier: intruder0007.Lumo
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: lumo_v0.4.0_windows_amd64/lumo.exe
    PortableCommandAlias: lumo
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/intruder0007/Lumo/releases/download/v0.4.0/lumo_v0.4.0_windows_amd64.zip
    InstallerSha256: 4157CBD2AC60553DBFFC1462C795617D7045CA1AD42BB24302804A89655E7B72
ManifestType: installer
ManifestVersion: 1.6.0
