# Created for github.com/intruder0007/Cli. See docs/architecture/distribution-protocol.md.
PackageIdentifier: intruder0007.Cli
PackageVersion: 0.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: cli_v0.3.0_windows_amd64/bootstrap.exe
    PortableCommandAlias: bootstrap
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/intruder0007/Cli/releases/download/v0.3.0/cli_v0.3.0_windows_amd64.zip
    InstallerSha256: 05CE82ABDE6942CA3236B41EE8C39EABFD483C16FF0B1125026E5DF2FD53D427
ManifestType: installer
ManifestVersion: 1.6.0
