// Package integration is a black-box end-to-end test: it builds the real
// cli binary and every V1 plugin, runs `bootstrap new` non-interactively,
// and verifies the generated project actually builds and passes its own
// tests, per ADR-0004's quality bar. It has no import dependency on
// core/sdk — it only shells out to `go build` and the built binaries,
// exactly as a real user would.
package integration

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := filepath.Abs(filepath.Join(wd, "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}

func buildBinary(t *testing.T, root, pkgDir, outPath string) {
	t.Helper()
	cmd := exec.Command("go", "build", "-o", outPath, "./"+pkgDir)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build ./%s: %v\n%s", pkgDir, err, out)
	}
}

func copyFile(t *testing.T, src, dst string) {
	t.Helper()
	data, err := os.ReadFile(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestEndToEndGenerateGoRestAPI builds the whole system fresh and proves
// the V1 promise: bootstrap new -> a working, tested Go REST API project
// with all three capabilities applied.
func TestEndToEndGenerateGoRestAPI(t *testing.T) {
	root := repoRoot(t)
	bin := t.TempDir()

	cliPath := filepath.Join(bin, exeName("bootstrap"))
	buildBinary(t, root, "cli", cliPath)

	templateDir := filepath.Join(bin, "templates", "go-rest-api")
	if err := os.MkdirAll(templateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	buildBinary(t, root, "templates/go-rest-api", filepath.Join(templateDir, exeName("go-rest-api")))
	copyFile(t, filepath.Join(root, "templates", "go-rest-api", "plugin.json"), filepath.Join(templateDir, "plugin.json"))

	capabilitiesDir := filepath.Join(bin, "plugins", "builtin")
	for _, cap := range []string{"git-init", "readme", "github-actions-ci"} {
		d := filepath.Join(capabilitiesDir, cap)
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
		buildBinary(t, root, "plugins/builtin/"+cap, filepath.Join(d, exeName(cap)))
		copyFile(t, filepath.Join(root, "plugins", "builtin", cap, "plugin.json"), filepath.Join(d, "plugin.json"))
	}

	genParent := t.TempDir()
	const projectName = "e2e-demo"

	cmd := exec.Command(cliPath, "new", projectName,
		"--project-type", "backend-service",
		"--language", "go",
		"--framework", "rest-api",
		"--capabilities", "git-init,readme,github-actions-ci",
		"--theme", "minimal",
	)
	cmd.Dir = genParent
	cmd.Env = append(os.Environ(), "CLI_PLUGIN_DIRS="+filepath.Join(bin, "templates")+string(os.PathListSeparator)+capabilitiesDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("bootstrap new failed: %v\n%s", err, out)
	}

	projectDir := filepath.Join(genParent, projectName)

	expected := []string{
		"go.mod", "main.go",
		filepath.Join("internal", "http", "router.go"),
		filepath.Join("internal", "http", "router_test.go"),
		"Makefile", "README.md", ".gitignore",
		".git",
		filepath.Join(".github", "workflows", "ci.yml"),
	}
	for _, f := range expected {
		if _, err := os.Stat(filepath.Join(projectDir, f)); err != nil {
			t.Errorf("expected generated path %s: %v", f, err)
		}
	}

	readme, err := os.ReadFile(filepath.Join(projectDir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(readme), "Generated by [Cli]") {
		t.Errorf("README.md missing the readme-capability footer:\n%s", readme)
	}

	buildCmd := exec.Command("go", "build", "./...")
	buildCmd.Dir = projectDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated project failed to build: %v\n%s", err, out)
	}

	testCmd := exec.Command("go", "test", "./...")
	testCmd.Dir = projectDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("generated project failed its own tests: %v\n%s", err, out)
	}

	logCmd := exec.Command("git", "log", "--oneline")
	logCmd.Dir = projectDir
	out, err := logCmd.CombinedOutput()
	if err != nil || strings.TrimSpace(string(out)) == "" {
		t.Fatalf("expected git-init to have created a commit: %v\n%s", err, out)
	}
}
