// Command typescript-rest-api generates a minimal, working TypeScript
// HTTP API service. The plugin itself is Go (there's no Node.js/
// TypeScript SDK yet — see docs/architecture/roadmap.md), but what it
// generates is TypeScript source. Same quality bar as go-rest-api/
// node-rest-api (ADR-0004): the generated project must actually run
// its own test suite, standalone, offline.
//
// Runs .ts files directly via Node's built-in type stripping (stable
// since Node ~22.6, explicitly requested with
// --experimental-strip-types for compatibility across the whole
// supported Node range) — no tsc, no npm install, matching
// node-rest-api's zero-dependency philosophy. This means the
// generated project doesn't typecheck as part of `npm test`; its
// README says so.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type typescriptRestAPITemplate struct{}

func (typescriptRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"package.json":   packageJSONFile(req.ProjectName),
		"tsconfig.json":  tsconfigJSONFile(),
		"server.ts":      serverTSFile(),
		"server.test.ts": serverTestTSFile(),
		"README.md":      readmeFile(req.ProjectName),
		".gitignore":     gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"npm test",
			"npm start # serves on :8080, GET /healthz",
		},
	}, nil
}

func packageJSONFile(projectName string) string {
	return fmt.Sprintf(`{
  "name": %q,
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node --experimental-strip-types server.ts",
    "test": "node --experimental-strip-types --test"
  }
}
`, projectName)
}

func tsconfigJSONFile() string {
	return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "erasableSyntaxOnly": true,
    "verbatimModuleSyntax": true
  },
  "include": ["*.ts"]
}
`
}

func serverTSFile() string {
	return `import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { pathToFileURL } from 'node:url';

interface HealthResponse {
  status: 'ok';
}

export function createApp() {
  return createServer((req: IncomingMessage, res: ServerResponse) => {
    if (req.method === 'GET' && req.url === '/healthz') {
      const body: HealthResponse = { status: 'ok' };
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(body));
      return;
    }
    res.writeHead(404);
    res.end();
  });
}

// pathToFileURL (not raw ` + "`file://${process.argv[1]}`" + ` string interpolation)
// is required for this "am I the entrypoint" check to work on Windows:
// import.meta.url is a properly-encoded file:// URL with forward
// slashes, but process.argv[1] is a raw OS path with backslashes on
// Windows, so a plain string comparison never matches there.
if (import.meta.url === pathToFileURL(process.argv[1]!).href) {
  const port = 8080;
  createApp().listen(port, () => {
    console.log(` + "`listening on :${port}`" + `);
  });
}
`
}

func serverTestTSFile() string {
	return `import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from './server.ts';

test('GET /healthz returns ok', async () => {
  const app = createApp();
  await new Promise<void>((resolve) => app.listen(0, resolve));
  const address = app.address();
  if (address === null || typeof address === 'string') {
    throw new Error('expected a net.AddressInfo');
  }

  try {
    const res = await fetch(` + "`http://localhost:${address.port}/healthz`" + `);
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.deepEqual(body, { status: 'ok' });
  } finally {
    app.close();
  }
});
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A TypeScript HTTP API service, generated by Lumo.

## Run

`+"```sh\nnpm start\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\":\"ok\"}`"+`.

## Test

`+"```sh\nnpm test\n```"+`

Uses Node's built-in test runner and built-in `+"`fetch`"+`, running the
`+"`.ts`"+` sources directly via Node's built-in type stripping — no
`+"`tsc`"+`, no `+"`npm install`"+`. This means `+"`npm test`"+` does not typecheck the
project; add `+"`typescript`"+` as a devDependency and run `+"`tsc --noEmit`"+`
separately if you want that.
`, projectName)
}

func gitignoreFile() string {
	return "node_modules/\n"
}

func main() {
	sdk.Serve(typescriptRestAPITemplate{})
}
