// Command kotlin-cli generates a minimal, working Kotlin command-line
// tool. The plugin itself is Go (there's no Kotlin SDK yet — see
// docs/architecture/roadmap.md), but what it generates is Kotlin
// source. Same quality bar as go-rest-api/node-rest-api (ADR-0004):
// the generated project must actually build and pass its own tests,
// standalone, offline.
//
// Deliberately a CLI tool, not an HTTP service, and deliberately
// plain kotlinc, not Gradle: a Gradle-wrapper project needs a first
// fetch of the Gradle distribution (and, once building anything real,
// usually the Kotlin stdlib/plugin from Maven Central too), which
// works against the "zero deps, offline-buildable" bar every other
// template holds. Plain `kotlinc ... -include-runtime -d app.jar`
// bundles the Kotlin runtime into the jar directly — nothing to fetch
// beyond having kotlinc itself installed.
//
// NOT LOCALLY BUILDABLE/TESTABLE IN THIS ENVIRONMENT: no Kotlin
// compiler was available where this template was written. Written
// carefully against standard Kotlin idioms and cross-checked against
// the Kotlin documentation, but the first real verification of the
// generated project is this repository's CI run
// (TestEndToEndGenerateKotlinCLI), not a local one. Treat an initial
// red CI run as expected, not a process failure.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type kotlinCLITemplate struct{}

func (kotlinCLITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"src/Calc.kt":      calcKtFile(),
		"src/Main.kt":      mainKtFile(),
		"test/CalcTest.kt": calcTestKtFile(),
		"README.md":        readmeFile(req.ProjectName),
		".gitignore":       gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"kotlinc src/Calc.kt test/CalcTest.kt -include-runtime -d test.jar && java -jar test.jar",
			"kotlinc src/Calc.kt src/Main.kt -include-runtime -d app.jar",
			"java -jar app.jar 2 3 # prints 5",
		},
	}, nil
}

func calcKtFile() string {
	return `fun add(a: Int, b: Int): Int = a + b
`
}

func mainKtFile() string {
	return `fun main(args: Array<String>) {
    if (args.size != 2) {
        System.err.println("usage: <a> <b>")
        kotlin.system.exitProcess(1)
    }
    val a = args[0].toInt()
    val b = args[1].toInt()
    println(add(a, b))
}
`
}

func calcTestKtFile() string {
	return `fun main() {
    check(add(2, 3) == 5) { "expected add(2, 3) == 5" }
    check(add(-1, 1) == 0) { "expected add(-1, 1) == 0" }
    check(add(0, 0) == 0) { "expected add(0, 0) == 0" }
    println("all tests passed")
}
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Kotlin command-line tool, generated by Lumo.

## Build & run

`+"```sh\nkotlinc src/Calc.kt src/Main.kt -include-runtime -d app.jar\njava -jar app.jar 2 3   # prints 5\n```"+`

## Test

`+"```sh\nkotlinc src/Calc.kt test/CalcTest.kt -include-runtime -d test.jar\njava -jar test.jar\n```"+`

`+"`CalcTest.kt`"+` is a plain file with a `+"`main`"+` function and Kotlin's
built-in `+"`check()`"+` (no test framework). Plain `+"`kotlinc`"+`, not Gradle: no
build tool distribution or dependency to fetch, just the Kotlin
compiler itself.
`, projectName)
}

func gitignoreFile() string {
	return "*.jar\n"
}

func main() {
	sdk.Serve(kotlinCLITemplate{})
}
