// Command readme is a capability plugin: it appends a "generated by"
// footer to the project's README.md (written earlier by the template
// plugin), demonstrating a capability that modifies rather than only
// adds files.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
)

const footer = "\n---\n\nGenerated by [Lumo](https://github.com/intruder0007/Lumo).\n"

type readmeCapability struct{}

func (readmeCapability) Apply(req sdk.ApplyRequest) (sdk.ApplyResponse, error) {
	path := filepath.Join(req.TargetDir, "README.md")

	existing, err := os.ReadFile(path)
	modified := err == nil

	content := string(existing) + footer
	if !modified {
		content = fmt.Sprintf("# %s\n%s", req.ProjectName, footer)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return sdk.ApplyResponse{}, fmt.Errorf("writing README.md: %w", err)
	}

	resp := sdk.ApplyResponse{}
	if modified {
		resp.FilesModified = []string{"README.md"}
	} else {
		resp.FilesWritten = []string{"README.md"}
	}
	return resp, nil
}

func main() {
	sdk.Serve(readmeCapability{})
}
