// Command node-rest-api is V1's second template plugin: it generates a
// minimal, working Node.js HTTP API service. The plugin itself is Go
// (there's no Node.js SDK yet — see docs/architecture/roadmap.md), but
// what it generates is a genuinely different language, the first real
// proof of "cross-language" bootstrapping. Same quality bar as
// go-rest-api (ADR-0004): the generated project must actually run its
// own test suite, standalone, offline. Uses only Node's built-in
// modules (node:http, node:test, node:assert, global fetch) — zero npm
// dependencies, so `npm test` never needs `npm install`.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type nodeRestAPITemplate struct{}

func (nodeRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"package.json":   packageJSONFile(req.ProjectName),
		"server.js":      serverJSFile(),
		"server.test.js": serverTestJSFile(),
		"README.md":      readmeFile(req.ProjectName),
		".gitignore":     gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"npm test",
			"npm start # serves on :8080, GET /healthz",
		},
	}, nil
}

func packageJSONFile(projectName string) string {
	return fmt.Sprintf(`{
  "name": %q,
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node server.js",
    "test": "node --test"
  }
}
`, projectName)
}

func serverJSFile() string {
	return `import { createServer } from 'node:http';
import { pathToFileURL } from 'node:url';

export function createApp() {
  return createServer((req, res) => {
    if (req.method === 'GET' && req.url === '/healthz') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok' }));
      return;
    }
    res.writeHead(404);
    res.end();
  });
}

// pathToFileURL (not raw ` + "`file://${process.argv[1]}`" + ` string interpolation)
// is required for this "am I the entrypoint" check to work on Windows:
// import.meta.url is a properly-encoded file:// URL with forward
// slashes, but process.argv[1] is a raw OS path with backslashes on
// Windows, so a plain string comparison never matches there.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const port = 8080;
  createApp().listen(port, () => {
    console.log(` + "`listening on :${port}`" + `);
  });
}
`
}

func serverTestJSFile() string {
	return `import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from './server.js';

test('GET /healthz returns ok', async () => {
  const app = createApp();
  await new Promise((resolve) => app.listen(0, resolve));
  const port = app.address().port;

  try {
    const res = await fetch(` + "`http://localhost:${port}/healthz`" + `);
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.deepEqual(body, { status: 'ok' });
  } finally {
    app.close();
  }
});
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Node.js HTTP API service, generated by Lumo.

## Run

`+"```sh\nnpm start\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\":\"ok\"}`"+`.

## Test

`+"```sh\nnpm test\n```"+`

Uses Node's built-in test runner (`+"`node --test`"+`) and built-in `+"`fetch`"+` —
no `+"`npm install`"+` needed.
`, projectName)
}

func gitignoreFile() string {
	return "node_modules/\n"
}

func main() {
	sdk.Serve(nodeRestAPITemplate{})
}
