// Command python-rest-api generates a minimal, working Python HTTP API
// service. The plugin itself is Go (there's no Python SDK yet — see
// docs/architecture/roadmap.md), but what it generates is Python
// source. Same quality bar as go-rest-api/node-rest-api (ADR-0004):
// the generated project must actually run its own test suite,
// standalone, offline.
//
// Uses only http.server/unittest/urllib (stdlib) — zero pip installs,
// matching node-rest-api's zero-dependency philosophy.
//
// NOT LOCALLY BUILDABLE/TESTABLE IN THIS ENVIRONMENT: no working
// Python interpreter was available where this template was written
// (only a Windows Store alias stub). Written carefully against
// standard http.server/unittest idioms and cross-checked against the
// Python documentation, but the first real verification of the
// generated project is this repository's CI run
// (TestEndToEndGeneratePythonRestAPI), not a local one. Treat an
// initial red CI run as expected, not a process failure.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type pythonRestAPITemplate struct{}

func (pythonRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"server.py":      serverPYFile(),
		"test_server.py": testServerPYFile(),
		"README.md":      readmeFile(req.ProjectName),
		".gitignore":     gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"python -m unittest discover",
			"python server.py # serves on :8080, GET /healthz",
		},
	}, nil
}

func serverPYFile() string {
	return `"""A minimal HTTP API service, generated by Lumo.

Uses only the standard library (http.server) -- no pip install needed.
"""
import json
from http.server import BaseHTTPRequestHandler, HTTPServer


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/healthz":
            body = json.dumps({"status": "ok"}).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        self.send_response(404)
        self.end_headers()

    def log_message(self, format, *args):
        # Quiet by default; comment this out to see request logs.
        pass


def create_app(host="0.0.0.0", port=8080):
    return HTTPServer((host, port), Handler)


if __name__ == "__main__":
    app = create_app()
    print("listening on :8080")
    app.serve_forever()
`
}

func testServerPYFile() string {
	return `import json
import threading
import unittest
import urllib.request

from server import create_app


class HealthzTest(unittest.TestCase):
    def test_healthz_returns_ok(self):
        app = create_app(host="127.0.0.1", port=0)
        thread = threading.Thread(target=app.serve_forever)
        thread.daemon = True
        thread.start()
        try:
            port = app.server_address[1]
            url = "http://127.0.0.1:%d/healthz" % port
            with urllib.request.urlopen(url) as resp:
                self.assertEqual(resp.status, 200)
                body = json.loads(resp.read())
                self.assertEqual(body, {"status": "ok"})
        finally:
            app.shutdown()
            thread.join()


if __name__ == "__main__":
    unittest.main()
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Python HTTP API service, generated by Lumo.

## Run

`+"```sh\npython server.py\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\": \"ok\"}`"+`.

## Test

`+"```sh\npython -m unittest discover\n```"+`

Uses only the standard library (`+"`http.server`"+`, `+"`unittest`"+`,
`+"`urllib.request`"+`) — no `+"`pip install`"+` needed.
`, projectName)
}

func gitignoreFile() string {
	return "__pycache__/\n*.pyc\n"
}

func main() {
	sdk.Serve(pythonRestAPITemplate{})
}
