// Command cpp-cli generates a minimal, working C++ command-line tool.
// The plugin itself is Go (there's no C++ SDK yet — see
// docs/architecture/roadmap.md), but what it generates is C++ source.
// Same quality bar as go-rest-api/node-rest-api (ADR-0004): the
// generated project must actually build and pass its own tests,
// standalone, offline.
//
// Deliberately a CLI tool, not an HTTP service like the other
// templates: this repo's only local C++ toolchain is an old MinGW
// g++ 6.3.0 with no CMake, so cross-platform socket code (needed for
// an HTTP server, Winsock vs POSIX sockets) isn't something this
// template can be locally verified against. A Makefile + g++
// -std=c++14 build/test a small library function instead — no
// networking, no extra deps, genuinely verifiable with what's
// actually installed. A CMake-based and/or HTTP variant is a natural
// follow-up once CI coverage exists to verify it (see the PR
// description).
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type cppCLITemplate struct{}

func (cppCLITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"Makefile":           makefileFile(),
		"include/calc.hpp":   calcHPPFile(),
		"src/calc.cpp":       calcCPPFile(),
		"src/main.cpp":       mainCPPFile(),
		"test/test_main.cpp": testMainCPPFile(),
		"README.md":          readmeFile(req.ProjectName),
		".gitignore":         gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"make build",
			"make test",
			"./bin/app 2 3 # prints 5",
		},
	}, nil
}

func makefileFile() string {
	return `CXX ?= g++
CXXFLAGS := -std=c++14 -Wall -Iinclude

ifeq ($(OS),Windows_NT)
EXE := .exe
else
EXE :=
endif

.PHONY: build test clean

build: bin/app$(EXE)

bin/app$(EXE): src/main.cpp src/calc.cpp include/calc.hpp
	mkdir -p bin
	$(CXX) $(CXXFLAGS) -o bin/app$(EXE) src/main.cpp src/calc.cpp

test: bin/test_calc$(EXE)
	./bin/test_calc$(EXE)

bin/test_calc$(EXE): test/test_main.cpp src/calc.cpp include/calc.hpp
	mkdir -p bin
	$(CXX) $(CXXFLAGS) -o bin/test_calc$(EXE) test/test_main.cpp src/calc.cpp

clean:
	rm -rf bin
`
}

func calcHPPFile() string {
	return `#pragma once

int add(int a, int b);
`
}

func calcCPPFile() string {
	return `#include "../include/calc.hpp"

int add(int a, int b) { return a + b; }
`
}

func mainCPPFile() string {
	return `#include <cstdlib>
#include <iostream>

#include "../include/calc.hpp"

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "usage: " << argv[0] << " <a> <b>" << std::endl;
        return 1;
    }
    int a = std::atoi(argv[1]);
    int b = std::atoi(argv[2]);
    std::cout << add(a, b) << std::endl;
    return 0;
}
`
}

func testMainCPPFile() string {
	return `#include <cassert>
#include <iostream>

#include "../include/calc.hpp"

int main() {
    assert(add(2, 3) == 5);
    assert(add(-1, 1) == 0);
    assert(add(0, 0) == 0);
    std::cout << "all tests passed" << std::endl;
    return 0;
}
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A C++ command-line tool, generated by Lumo.

## Build

`+"```sh\nmake build\n```"+`

`+"```sh\n./bin/app 2 3   # prints 5\n```"+`

## Test

`+"```sh\nmake test\n```"+`

Uses a plain `+"`assert`"+`-based `+"`test_main.cpp`"+` (no test framework) and a
plain Makefile with `+"`g++ -std=c++14`"+` (no CMake, no extra
dependencies) — `+"`make build`"+`/`+"`make test`"+` never need anything beyond a
C++ compiler.
`, projectName)
}

func gitignoreFile() string {
	return "/bin/\n"
}

func main() {
	sdk.Serve(cppCLITemplate{})
}
