// Command rust-rest-api generates a minimal, working Rust HTTP API
// service. The plugin itself is Go (there's no Rust SDK yet — see
// docs/architecture/roadmap.md), but what it generates is Rust source.
// Same quality bar as go-rest-api/node-rest-api (ADR-0004): the
// generated project must actually build and pass its own tests,
// standalone, offline.
//
// Uses std::net::TcpListener with a hand-rolled HTTP request line
// parse — no external crates — matching node-rest-api's
// zero-dependency philosophy: `cargo build`/`cargo test` never need
// to fetch anything from crates.io.
package main

import (
	"fmt"

	sdk "github.com/intruder0007/Lumo/sdk/go/sdk"
	"github.com/intruder0007/Lumo/sdk/go/sdk/fsutil"
)

type rustRestAPITemplate struct{}

func (rustRestAPITemplate) Generate(req sdk.GenerateRequest) (sdk.GenerateResponse, error) {
	files := map[string]string{
		"Cargo.toml":  cargoTOMLFile(req.ProjectName),
		"src/main.rs": mainRSFile(),
		"README.md":   readmeFile(req.ProjectName),
		".gitignore":  gitignoreFile(),
	}

	written, err := fsutil.WriteFiles(req.TargetDir, files)
	if err != nil {
		return sdk.GenerateResponse{}, err
	}

	return sdk.GenerateResponse{
		FilesWritten: written,
		NextSteps: []string{
			fmt.Sprintf("cd %s", req.ProjectName),
			"cargo build",
			"cargo test",
			"cargo run # serves on :8080, GET /healthz",
		},
	}, nil
}

func cargoTOMLFile(projectName string) string {
	return fmt.Sprintf(`[package]
name = %q
version = "0.1.0"
edition = "2021"
`, projectName)
}

func mainRSFile() string {
	return `use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};

fn handle_connection(stream: &mut TcpStream) -> std::io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    reader.read_line(&mut request_line)?;

    // Drain remaining header lines up to the blank line separating
    // headers from body, so the client's write isn't left hanging.
    loop {
        let mut line = String::new();
        let n = reader.read_line(&mut line)?;
        if n == 0 || line == "\r\n" || line == "\n" {
            break;
        }
    }

    let body = "{\"status\":\"ok\"}";
    let response = if request_line.starts_with("GET /healthz ") {
        format!(
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
            body.len(),
            body
        )
    } else {
        "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n".to_string()
    };
    stream.write_all(response.as_bytes())
}

fn main() -> std::io::Result<()> {
    let listener = TcpListener::bind("0.0.0.0:8080")?;
    println!("listening on :8080");
    for stream in listener.incoming() {
        let mut stream = stream?;
        if let Err(e) = handle_connection(&mut stream) {
            eprintln!("connection error: {e}");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    #[test]
    fn healthz_returns_ok() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();

        std::thread::spawn(move || {
            if let Ok((mut stream, _)) = listener.accept() {
                let _ = handle_connection(&mut stream);
            }
        });

        let mut client = TcpStream::connect(addr).unwrap();
        client
            .write_all(b"GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n")
            .unwrap();

        let mut response = String::new();
        client.read_to_string(&mut response).unwrap();

        assert!(response.starts_with("HTTP/1.1 200 OK"));
        assert!(response.contains("{\"status\":\"ok\"}"));
    }

    #[test]
    fn unknown_path_returns_404() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();

        std::thread::spawn(move || {
            if let Ok((mut stream, _)) = listener.accept() {
                let _ = handle_connection(&mut stream);
            }
        });

        let mut client = TcpStream::connect(addr).unwrap();
        client
            .write_all(b"GET /nope HTTP/1.1\r\nHost: localhost\r\n\r\n")
            .unwrap();

        let mut response = String::new();
        client.read_to_string(&mut response).unwrap();

        assert!(response.starts_with("HTTP/1.1 404 Not Found"));
    }
}
`
}

func readmeFile(projectName string) string {
	return fmt.Sprintf(`# %s

A Rust HTTP API service, generated by Lumo.

## Run

`+"```sh\ncargo run\n```"+`

Serves on :8080. `+"`GET /healthz`"+` returns `+"`{\"status\":\"ok\"}`"+`.

## Test

`+"```sh\ncargo test\n```"+`

Uses `+"`std::net`"+` directly (a hand-rolled HTTP request-line parse) — no
external crates, so `+"`cargo build`"+`/`+"`cargo test`"+` never need to fetch
anything from crates.io.
`, projectName)
}

func gitignoreFile() string {
	return "/target\n"
}

func main() {
	sdk.Serve(rustRestAPITemplate{})
}
